import { PrismaClient, AccountType } from '@prisma/client'

const prisma = new PrismaClient()

export const defaultAccounts = [
  { code: '0000', name: 'Вспомогательный (ввод начальных остатков)', type: AccountType.ACTIVE_PASSIVE },
  { code: '0100', name: 'СЧЕТА УЧЁТА ОСНОВНЫХ СРЕДСТВ', type: AccountType.ACTIVE },
  { code: '0110', name: 'Земля', type: AccountType.ACTIVE },
  { code: '0111', name: 'Благоустройство земли', type: AccountType.ACTIVE },
  { code: '0112', name: 'Благоустройство основных средств, полученных по договору финансовой аренды', type: AccountType.ACTIVE },
  { code: '0120', name: 'Здания, сооружения и передаточные устройства', type: AccountType.ACTIVE },
  { code: '0130', name: 'Машины и оборудование', type: AccountType.ACTIVE },
  { code: '0140', name: 'Мебель и офисное оборудование', type: AccountType.ACTIVE },
  { code: '0150', name: 'Компьютерное оборудование и вычислительная техника', type: AccountType.ACTIVE },
  { code: '0160', name: 'Транспортные средства', type: AccountType.ACTIVE },
  { code: '0170', name: 'Рабочий и продуктивный скот', type: AccountType.ACTIVE },
  { code: '0180', name: 'Многолетние насаждения', type: AccountType.ACTIVE },
  { code: '0190', name: 'Прочие основные средства', type: AccountType.ACTIVE },
  { code: '0199', name: 'Законсервированные основные средства', type: AccountType.ACTIVE },
  { code: '0200', name: 'СЧЕТА УЧЁТА ИЗНОСА ОСНОВНЫХ СРЕДСТВ', type: AccountType.ACTIVE },
  { code: '0211', name: 'Износ благоустройства земли', type: AccountType.ACTIVE },
  { code: '0212', name: 'Износ благоустройства основных средств, полученных по договору финансовой аренды', type: AccountType.ACTIVE },
  { code: '0220', name: 'Износ зданий, сооружений и передаточных устройств', type: AccountType.ACTIVE },
  { code: '0230', name: 'Износ машин и оборудования', type: AccountType.ACTIVE },
  { code: '0240', name: 'Износ мебели и офисного оборудования', type: AccountType.ACTIVE },
  { code: '0250', name: 'Износ компьютерного оборудования и вычислительной техники', type: AccountType.ACTIVE },
  { code: '0260', name: 'Износ транспортных средств', type: AccountType.ACTIVE },
  { code: '0270', name: 'Износ рабочего скота', type: AccountType.ACTIVE },
  { code: '0280', name: 'Износ многолетних насаждений', type: AccountType.ACTIVE },
  { code: '0290', name: 'Износ прочих основных средств', type: AccountType.ACTIVE },
  { code: '0299', name: 'Износ основных средств, полученных по договору финансовой аренды', type: AccountType.ACTIVE },
  { code: '0300', name: 'СЧЕТА УЧЁТА ОСНОВНЫХ СРЕДСТВ, ПОЛУЧЕННЫХ ПО ДОГОВОРУ ФИНАНСОВОЙ АРЕНДЫ', type: AccountType.ACTIVE },
  { code: '0310', name: 'Основные средства, полученные по договору финансовой аренды', type: AccountType.ACTIVE },
  { code: '0400', name: 'СЧЕТА УЧЁТА НЕМАТЕРИАЛЬНЫХ АКТИВОВ', type: AccountType.ACTIVE },
  { code: '0410', name: 'Патенты, лицензии и ноу-хау', type: AccountType.ACTIVE },
  { code: '0420', name: 'Торговые марки, товарные знаки и промышленные образцы', type: AccountType.ACTIVE },
  { code: '0430', name: 'Программное обеспечение', type: AccountType.ACTIVE },
  { code: '0440', name: 'Права пользования землей и природными ресурсами', type: AccountType.ACTIVE },
  { code: '0460', name: 'Франчайз', type: AccountType.ACTIVE },
  { code: '0470', name: 'Авторские права', type: AccountType.ACTIVE },
  { code: '0480', name: 'Гудвилл', type: AccountType.ACTIVE },
  { code: '0490', name: 'Прочие нематериальные активы', type: AccountType.ACTIVE },
  { code: '0500', name: 'СЧЕТА УЧЁТА АМОРТИЗАЦИИ НЕМАТЕРИАЛЬНЫХ АКТИВОВ', type: AccountType.ACTIVE },
  { code: '0510', name: 'Амортизация патентов, лицензий и ноу-хау', type: AccountType.ACTIVE },
  { code: '0520', name: 'Амортизация торговых марок, товарных знаков и промышленных образцов', type: AccountType.ACTIVE },
  { code: '0530', name: 'Амортизация программного обеспечения', type: AccountType.ACTIVE },
  { code: '0540', name: 'Амортизация прав пользования землей и природными ресурсами', type: AccountType.ACTIVE },
  { code: '0550', name: 'Амортизация организационных расходов', type: AccountType.ACTIVE },
  { code: '0560', name: 'Амортизация франчайза', type: AccountType.ACTIVE },
  { code: '0570', name: 'Амортизация авторских прав', type: AccountType.ACTIVE },
  { code: '0590', name: 'Амортизация прочих нематериальных активов', type: AccountType.ACTIVE },
  { code: '0600', name: 'СЧЕТА УЧЁТА ДОЛГОСРОЧНЫХ ИНВЕСТИЦИЙ', type: AccountType.ACTIVE },
  { code: '0610', name: 'Ценные бумаги', type: AccountType.ACTIVE },
  { code: '0620', name: 'Инвестиции в дочерние хозяйственные общества', type: AccountType.ACTIVE },
  { code: '0630', name: 'Инвестиции в зависимые хозяйственные общества', type: AccountType.ACTIVE },
  { code: '0640', name: 'Инвестиции в предприятие с иностранным капиталом', type: AccountType.ACTIVE },
  { code: '0690', name: 'Прочие долгосрочные инвестиции', type: AccountType.ACTIVE },
  { code: '0700', name: 'СЧЕТА УЧЁТА ОБОРУДОВАНИЯ К УСТАНОВКЕ', type: AccountType.ACTIVE },
  { code: '0710', name: 'Оборудование к установке — отечественное', type: AccountType.ACTIVE },
  { code: '0720', name: 'Оборудование к установке — импортное', type: AccountType.ACTIVE },
  { code: '0800', name: 'СЧЕТА УЧЁТА КАПИТАЛЬНЫХ ВЛОЖЕНИЙ', type: AccountType.ACTIVE },
  { code: '0810', name: 'Незавершённое строительство', type: AccountType.ACTIVE },
  { code: '0820', name: 'Приобретение основных средств', type: AccountType.ACTIVE },
  { code: '0830', name: 'Приобретение нематериальных активов', type: AccountType.ACTIVE },
  { code: '0840', name: 'Формирование основного стада', type: AccountType.ACTIVE },
  { code: '0850', name: 'Капитальные вложения в благоустройство земли', type: AccountType.ACTIVE },
  { code: '0860', name: 'Капитальные вложения в основные средства, полученные по договору финансовой аренды', type: AccountType.ACTIVE },
  { code: '0890', name: 'Прочие капитальные вложения', type: AccountType.ACTIVE },
  { code: '0900', name: 'СЧЕТА УЧЁТА ДОЛГОСРОЧНОЙ ДЕБИТОРСКОЙ ЗАДОЛЖЕННОСТИ И ОТСРОЧЕННЫХ РАСХОДОВ', type: AccountType.ACTIVE },
  { code: '0910', name: 'Векселя полученные', type: AccountType.ACTIVE },
  { code: '0920', name: 'Платежи к получению по финансовой аренде', type: AccountType.ACTIVE },
  { code: '0930', name: 'Долгосрочная задолженность персонала', type: AccountType.ACTIVE },
  { code: '0940', name: 'Прочая долгосрочная дебиторская задолженность', type: AccountType.ACTIVE },
  { code: '0950', name: 'Отсроченный налог на прибыль по временным разницам', type: AccountType.ACTIVE },
  { code: '0960', name: 'Долгосрочные отсроченные расходы по дисконтам (скидкам)', type: AccountType.ACTIVE },
  { code: '0990', name: 'Прочие долгосрочные отсроченные расходы', type: AccountType.ACTIVE },
  { code: '1000', name: 'СЧЕТА УЧЁТА МАТЕРИАЛОВ', type: AccountType.ACTIVE },
  { code: '1010', name: 'Сырьё и материалы', type: AccountType.ACTIVE },
  { code: '1020', name: 'Покупные полуфабрикаты и комплектующие изделия', type: AccountType.ACTIVE },
  { code: '1030', name: 'Топливо', type: AccountType.ACTIVE },
  { code: '1040', name: 'Запасные части', type: AccountType.ACTIVE },
  { code: '1050', name: 'Строительные материалы', type: AccountType.ACTIVE },
  { code: '1060', name: 'Тара и тарные материалы', type: AccountType.ACTIVE },
  { code: '1070', name: 'Материалы, переданные в переработку на сторону', type: AccountType.ACTIVE },
  { code: '1080', name: 'Инвентарь и хозяйственные принадлежности', type: AccountType.ACTIVE },
  { code: '1090', name: 'Прочие материалы', type: AccountType.ACTIVE },
  { code: '1100', name: 'СЧЕТА УЧЁТА ЖИВОТНЫХ НА ВЫРАЩИВАНИИ И ОТКОРМЕ', type: AccountType.ACTIVE },
  { code: '1110', name: 'Животные на выращивании', type: AccountType.ACTIVE },
  { code: '1120', name: 'Животные на откорме', type: AccountType.ACTIVE },
  { code: '1500', name: 'СЧЕТА УЧЁТА ЗАГОТОВЛЕНИЯ И ПРИОБРЕТЕНИЯ МАТЕРИАЛОВ', type: AccountType.ACTIVE },
  { code: '1510', name: 'Заготовление и приобретение материалов', type: AccountType.ACTIVE },
  { code: '1600', name: 'СЧЕТА УЧЁТА ОТКЛОНЕНИЙ В СТОИМОСТИ МАТЕРИАЛОВ', type: AccountType.ACTIVE },
  { code: '1610', name: 'Отклонения в стоимости материалов', type: AccountType.ACTIVE },
  { code: '2000', name: 'СЧЕТА УЧЁТА ОСНОВНОГО ПРОИЗВОДСТВА', type: AccountType.ACTIVE },
  { code: '2010', name: 'Основное производство', type: AccountType.ACTIVE },
  { code: '2100', name: 'СЧЕТА УЧЁТА ПОЛУФАБРИКАТОВ СОБСТВЕННОГО ПРОИЗВОДСТВА', type: AccountType.ACTIVE },
  { code: '2110', name: 'Полуфабрикаты собственного производства', type: AccountType.ACTIVE },
  { code: '2300', name: 'СЧЕТА УЧЁТА ВСПОМОГАТЕЛЬНЫХ ПРОИЗВОДСТВ', type: AccountType.ACTIVE },
  { code: '2310', name: 'Вспомогательное производство', type: AccountType.ACTIVE },
  { code: '2500', name: 'СЧЕТА УЧЁТА ОБЩЕПРОИЗВОДСТВЕННЫХ РАСХОДОВ', type: AccountType.ACTIVE },
  { code: '2510', name: 'Общепроизводственные расходы', type: AccountType.ACTIVE },
  { code: '2600', name: 'СЧЕТА УЧЁТА БРАКА В ПРОИЗВОДСТВЕ', type: AccountType.ACTIVE },
  { code: '2610', name: 'Брак в производстве', type: AccountType.ACTIVE },
  { code: '2700', name: 'СЧЕТА УЧЁТА ОБСЛУЖИВАЮЩИХ ХОЗЯЙСТВ', type: AccountType.ACTIVE },
  { code: '2710', name: 'Обслуживающие хозяйства', type: AccountType.ACTIVE },
  { code: '2800', name: 'СЧЕТА УЧЁТА ГОТОВОЙ ПРОДУКЦИИ', type: AccountType.ACTIVE },
  { code: '2810', name: 'Готовая продукция на складе', type: AccountType.ACTIVE },
  { code: '2820', name: 'Готовая продукция на выставке', type: AccountType.ACTIVE },
  { code: '2830', name: 'Готовая продукция, переданная на комиссию', type: AccountType.ACTIVE },
  { code: '2900', name: 'СЧЕТА УЧЁТА ТОВАРОВ', type: AccountType.ACTIVE },
  { code: '2910', name: 'Товары на складах', type: AccountType.ACTIVE },
  { code: '2920', name: 'Товары в розничной торговле', type: AccountType.ACTIVE },
  { code: '2930', name: 'Товары на выставке', type: AccountType.ACTIVE },
  { code: '2940', name: 'Предметы проката', type: AccountType.ACTIVE },
  { code: '2950', name: 'Тара под товаром и порожняя', type: AccountType.ACTIVE },
  { code: '2960', name: 'Товары, переданные на комиссию', type: AccountType.ACTIVE },
  { code: '2970', name: 'Товары в пути', type: AccountType.ACTIVE },
  { code: '2980', name: 'Торговая наценка', type: AccountType.ACTIVE },
  { code: '2990', name: 'Прочие товары', type: AccountType.ACTIVE },
  { code: '3100', name: 'СЧЕТА УЧЁТА РАСХОДОВ БУДУЩИХ ПЕРИОДОВ', type: AccountType.ACTIVE },
  { code: '3110', name: 'Предоплаченная оперативная аренда', type: AccountType.ACTIVE },
  { code: '3120', name: 'Предоплаченные услуги', type: AccountType.ACTIVE },
  { code: '3190', name: 'Прочие расходы будущих периодов', type: AccountType.ACTIVE },
  { code: '3200', name: 'СЧЕТА УЧЁТА ОТСРОЧЕННЫХ РАСХОДОВ', type: AccountType.ACTIVE },
  { code: '3210', name: 'Отсроченный налог на прибыль по временным разницам', type: AccountType.ACTIVE },
  { code: '3220', name: 'Отсроченные расходы по дисконтам (скидкам)', type: AccountType.ACTIVE },
  { code: '3290', name: 'Прочие отсроченные расходы', type: AccountType.ACTIVE },
  { code: '4000', name: 'СЧЕТА К ПОЛУЧЕНИЮ', type: AccountType.ACTIVE },
  { code: '4010', name: 'Счета к получению от покупателей и заказчиков', type: AccountType.ACTIVE },
  { code: '4020', name: 'Векселя полученные', type: AccountType.ACTIVE },
  { code: '4100', name: 'СЧЕТА К ПОЛУЧЕНИЮ ОТ ОБОСОБЛЕННЫХ ПОДРАЗДЕЛЕНИЙ, ДОЧЕРНИХ И ЗАВИСИМЫХ ХОЗЯЙСТВЕННЫХ ОБЩЕСТВ', type: AccountType.ACTIVE },
  { code: '4110', name: 'Счета к получению от обособленных подразделений', type: AccountType.ACTIVE },
  { code: '4120', name: 'Счета к получению от дочерних и зависимых хозяйственных обществ', type: AccountType.ACTIVE },
  { code: '4200', name: 'СЧЕТА УЧЁТА АВАНСОВ, ВЫДАННЫХ ПЕРСОНАЛУ', type: AccountType.ACTIVE },
  { code: '4210', name: 'Авансы, выданные по оплате труда', type: AccountType.ACTIVE },
  { code: '4220', name: 'Авансы, выданные на служебные командировки', type: AccountType.ACTIVE },
  { code: '4230', name: 'Авансы, выданные на общехозяйственные расходы', type: AccountType.ACTIVE },
  { code: '4290', name: 'Прочие авансы, выданные персоналу', type: AccountType.ACTIVE },
  { code: '4300', name: 'СЧЕТА УЧЁТА АВАНСОВ, ВЫДАННЫХ ПОСТАВЩИКАМ И ПОДРЯДЧИКАМ', type: AccountType.ACTIVE },
  { code: '4310', name: 'Авансы, выданные поставщикам и подрядчикам под ТМЦ', type: AccountType.ACTIVE },
  { code: '4320', name: 'Авансы, выданные поставщикам и подрядчикам под долгосрочные активы', type: AccountType.ACTIVE },
  { code: '4330', name: 'Прочие авансы выданные', type: AccountType.ACTIVE },
  { code: '4400', name: 'СЧЕТА УЧЁТА АВАНСОВЫХ ПЛАТЕЖЕЙ В БЮДЖЕТ', type: AccountType.ACTIVE },
  { code: '4410', name: 'Авансовые платежи по налогам и сборам в бюджетную систему (по видам)', type: AccountType.ACTIVE },
  { code: '4500', name: 'СЧЕТА УЧЁТА АВАНСОВЫХ ПЛАТЕЖЕЙ В ГОСУДАРСТВЕННЫЕ ЦЕЛЕВЫЕ ФОНДЫ И ПО СТРАХОВАНИЮ', type: AccountType.ACTIVE },
  { code: '4510', name: 'Авансовые платежи по страхованию', type: AccountType.ACTIVE },
  { code: '4520', name: 'Авансовые платежи в государственные целевые фонды', type: AccountType.ACTIVE },
  { code: '4600', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ УЧРЕДИТЕЛЕЙ ПО ВКЛАДАМ В УСТАВНЫЙ КАПИТАЛ', type: AccountType.ACTIVE },
  { code: '4610', name: 'Задолженность учредителей по вкладам в уставный капитал', type: AccountType.ACTIVE },
  { code: '4700', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ ПЕРСОНАЛА ПО ПРОЧИМ ОПЕРАЦИЯМ', type: AccountType.ACTIVE },
  { code: '4710', name: 'Задолженность персонала по товарам, реализованным в кредит', type: AccountType.ACTIVE },
  { code: '4720', name: 'Задолженность персонала по предоставленным займам', type: AccountType.ACTIVE },
  { code: '4730', name: 'Задолженность персонала по возмещению материального ущерба', type: AccountType.ACTIVE },
  { code: '4790', name: 'Прочая задолженность персонала', type: AccountType.ACTIVE },
  { code: '4800', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ РАЗНЫХ ДЕБИТОРОВ', type: AccountType.ACTIVE },
  { code: '4810', name: 'Платежи к получению по финансовой аренде — текущая часть', type: AccountType.ACTIVE },
  { code: '4820', name: 'Платежи к получению по оперативной аренде', type: AccountType.ACTIVE },
  { code: '4830', name: 'Проценты к получению', type: AccountType.ACTIVE },
  { code: '4840', name: 'Дивиденды к получению', type: AccountType.ACTIVE },
  { code: '4850', name: 'Роялти к получению', type: AccountType.ACTIVE },
  { code: '4860', name: 'Счета к получению по претензиям', type: AccountType.ACTIVE },
  { code: '4890', name: 'Задолженность прочих дебиторов', type: AccountType.ACTIVE },
  { code: '4900', name: 'СЧЕТА УЧЁТА РЕЗЕРВА ПО СОМНИТЕЛЬНЫМ ДОЛГАМ', type: AccountType.ACTIVE },
  { code: '4910', name: 'Резерв по сомнительным долгам', type: AccountType.ACTIVE },
  { code: '5000', name: 'СЧЕТА УЧЁТА ДЕНЕЖНЫХ СРЕДСТВ В КАССЕ', type: AccountType.ACTIVE },
  { code: '5010', name: 'Денежные средства в национальной валюте', type: AccountType.ACTIVE },
  { code: '5020', name: 'Денежные средства в иностранной валюте', type: AccountType.ACTIVE },
  { code: '5100', name: 'СЧЕТА УЧЁТА ДЕНЕЖНЫХ СРЕДСТВ НА РАСЧЁТНОМ СЧЁТЕ', type: AccountType.ACTIVE },
  { code: '5110', name: 'Расчётный счёт', type: AccountType.ACTIVE },
  { code: '5200', name: 'СЧЕТА УЧЁТА ДЕНЕЖНЫХ СРЕДСТВ В ИНОСТРАННОЙ ВАЛЮТЕ', type: AccountType.ACTIVE },
  { code: '5210', name: 'Валютные счета внутри страны', type: AccountType.ACTIVE },
  { code: '5220', name: 'Валютные счета за рубежом', type: AccountType.ACTIVE },
  { code: '5500', name: 'СЧЕТА УЧЁТА ДЕНЕЖНЫХ СРЕДСТВ НА СПЕЦИАЛЬНЫХ СЧЕТАХ В БАНКЕ', type: AccountType.ACTIVE },
  { code: '5510', name: 'Аккредитивы', type: AccountType.ACTIVE },
  { code: '5520', name: 'Чековые книжки', type: AccountType.ACTIVE },
  { code: '5530', name: 'Прочие специальные счета', type: AccountType.ACTIVE },
  { code: '5600', name: 'СЧЕТА УЧЁТА ДЕНЕЖНЫХ ЭКВИВАЛЕНТОВ', type: AccountType.ACTIVE },
  { code: '5610', name: 'Денежные эквиваленты (по видам)', type: AccountType.ACTIVE },
  { code: '5700', name: 'СЧЕТА УЧЁТА ДЕНЕЖНЫХ СРЕДСТВ (ПЕРЕВОДОВ) В ПУТИ', type: AccountType.ACTIVE },
  { code: '5710', name: 'Денежные средства (переводы) в пути', type: AccountType.ACTIVE },
  { code: '5800', name: 'СЧЕТА УЧЁТА КРАТКОСРОЧНЫХ ИНВЕСТИЦИЙ', type: AccountType.ACTIVE },
  { code: '5810', name: 'Ценные бумаги', type: AccountType.ACTIVE },
  { code: '5830', name: 'Краткосрочные займы выданные', type: AccountType.ACTIVE },
  { code: '5890', name: 'Прочие текущие инвестиции', type: AccountType.ACTIVE },
  { code: '5900', name: 'СЧЕТА УЧЁТА НЕДОСТАЧ И ПОТЕРЬ ОТ ПОРЧИ ЦЕННОСТЕЙ И ПРОЧИХ ТЕКУЩИХ АКТИВОВ', type: AccountType.ACTIVE },
  { code: '5910', name: 'Недостачи и потери от порчи ценностей', type: AccountType.ACTIVE },
  { code: '5920', name: 'Прочие текущие активы', type: AccountType.ACTIVE },
  { code: '6000', name: 'СЧЕТА К ОПЛАТЕ ПОСТАВЩИКАМ И ПОДРЯДЧИКАМ', type: AccountType.PASSIVE },
  { code: '6010', name: 'Счета к оплате поставщикам и подрядчикам', type: AccountType.PASSIVE },
  { code: '6020', name: 'Векселя выданные', type: AccountType.PASSIVE },
  { code: '6100', name: 'СЧЕТА К ОПЛАТЕ ОБОСОБЛЕННЫМ ПОДРАЗДЕЛЕНИЯМ, ДОЧЕРНИМ И ЗАВИСИМЫМ ХОЗЯЙСТВЕННЫМ ОБЩЕСТВАМ', type: AccountType.PASSIVE },
  { code: '6110', name: 'Счета к оплате обособленным подразделениям', type: AccountType.PASSIVE },
  { code: '6120', name: 'Счета к оплате дочерним и зависимым хозяйственным обществам', type: AccountType.PASSIVE },
  { code: '6200', name: 'СЧЕТА УЧЁТА ОТСРОЧЕННЫХ ОБЯЗАТЕЛЬСТВ', type: AccountType.PASSIVE },
  { code: '6210', name: 'Отсроченные доходы в виде дисконта (скидки)', type: AccountType.PASSIVE },
  { code: '6220', name: 'Отсроченные доходы в виде премии (надбавки)', type: AccountType.PASSIVE },
  { code: '6230', name: 'Прочие отсроченные доходы', type: AccountType.PASSIVE },
  { code: '6240', name: 'Отсроченные обязательства по налогам и другим обязательным платежам', type: AccountType.PASSIVE },
  { code: '6250', name: 'Обязательства по отсроченному налогу на прибыль по временным разницам', type: AccountType.PASSIVE },
  { code: '6290', name: 'Прочие отсроченные обязательства', type: AccountType.PASSIVE },
  { code: '6300', name: 'СЧЕТА УЧЁТА ПОЛУЧЕННЫХ АВАНСОВ', type: AccountType.PASSIVE },
  { code: '6310', name: 'Авансы, полученные от покупателей и заказчиков', type: AccountType.PASSIVE },
  { code: '6320', name: 'Авансы, полученные от подписчиков на акции', type: AccountType.PASSIVE },
  { code: '6390', name: 'Прочие полученные авансы', type: AccountType.PASSIVE },
  { code: '6400', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ ПО ПЛАТЕЖАМ В БЮДЖЕТ', type: AccountType.PASSIVE },
  { code: '6410', name: 'Задолженность по платежам в бюджет (по видам)', type: AccountType.PASSIVE },
  { code: '6500', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ ПО СТРАХОВАНИЮ И ПО ПЛАТЕЖАМ В ГОСУДАРСТВЕННЫЕ ЦЕЛЕВЫЕ ФОНДЫ', type: AccountType.PASSIVE },
  { code: '6510', name: 'Платежи по страхованию', type: AccountType.PASSIVE },
  { code: '6520', name: 'Платежи в государственные целевые фонды', type: AccountType.PASSIVE },
  { code: '6600', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ УЧРЕДИТЕЛЯМ', type: AccountType.PASSIVE },
  { code: '6610', name: 'Дивиденды к оплате', type: AccountType.PASSIVE },
  { code: '6620', name: 'Задолженность выбывающим учредителям по их доле', type: AccountType.PASSIVE },
  { code: '6630', name: 'Вклады учредителей по увеличению уставного капитала', type: AccountType.PASSIVE },
  { code: '6700', name: 'СЧЕТА УЧЁТА РАСЧЁТОВ С ПЕРСОНАЛОМ ПО ОПЛАТЕ ТРУДА', type: AccountType.PASSIVE },
  { code: '6710', name: 'Расчёты с персоналом по оплате труда', type: AccountType.PASSIVE },
  { code: '6720', name: 'Депонированная заработная плата', type: AccountType.PASSIVE },
  { code: '6800', name: 'СЧЕТА УЧЁТА КРАТКОСРОЧНЫХ КРЕДИТОВ И ЗАЙМОВ', type: AccountType.PASSIVE },
  { code: '6810', name: 'Краткосрочные банковские кредиты', type: AccountType.PASSIVE },
  { code: '6820', name: 'Краткосрочные займы', type: AccountType.PASSIVE },
  { code: '6830', name: 'Облигации к оплате', type: AccountType.PASSIVE },
  { code: '6840', name: 'Векселя к оплате', type: AccountType.PASSIVE },
  { code: '6900', name: 'СЧЕТА УЧЁТА ЗАДОЛЖЕННОСТИ РАЗНЫМ КРЕДИТОРАМ', type: AccountType.PASSIVE },
  { code: '6910', name: 'Оперативная аренда к оплате', type: AccountType.PASSIVE },
  { code: '6920', name: 'Начисленные проценты', type: AccountType.PASSIVE },
  { code: '6930', name: 'Задолженность по роялти', type: AccountType.PASSIVE },
  { code: '6940', name: 'Задолженность по гарантиям', type: AccountType.PASSIVE },
  { code: '6950', name: 'Долгосрочные обязательства — текущая часть', type: AccountType.PASSIVE },
  { code: '6960', name: 'Счета к оплате по претензиям', type: AccountType.PASSIVE },
  { code: '6970', name: 'Задолженность подотчётным лицам', type: AccountType.PASSIVE },
  { code: '6990', name: 'Прочие обязательства', type: AccountType.PASSIVE },
  { code: '7000', name: 'ДОЛГОСРОЧНЫЕ СЧЕТА К ОПЛАТЕ ПОСТАВЩИКАМ И ПОДРЯДЧИКАМ', type: AccountType.PASSIVE },
  { code: '7010', name: 'Счета к оплате поставщикам и подрядчикам', type: AccountType.PASSIVE },
  { code: '7020', name: 'Векселя выданные', type: AccountType.PASSIVE },
  { code: '7100', name: 'ДОЛГОСРОЧНАЯ ЗАДОЛЖЕННОСТЬ ОБОСОБЛЕННЫМ ПОДРАЗДЕЛЕНИЯМ, ДОЧЕРНИМ И ЗАВИСИМЫМ ХОЗЯЙСТВЕННЫМ ОБЩЕСТВАМ', type: AccountType.PASSIVE },
  { code: '7110', name: 'Долгосрочная задолженность обособленным подразделениям', type: AccountType.PASSIVE },
  { code: '7120', name: 'Долгосрочная задолженность дочерним и зависимым хозяйственным обществам', type: AccountType.PASSIVE },
  { code: '7200', name: 'СЧЕТА УЧЁТА ОТСРОЧЕННЫХ ДОЛГОСРОЧНЫХ ОБЯЗАТЕЛЬСТВ', type: AccountType.PASSIVE },
  { code: '7210', name: 'Долгосрочные отсроченные доходы в виде дисконта (скидки)', type: AccountType.PASSIVE },
  { code: '7220', name: 'Долгосрочные отсроченные доходы в виде премии (надбавки)', type: AccountType.PASSIVE },
  { code: '7230', name: 'Прочие долгосрочные отсроченные доходы', type: AccountType.PASSIVE },
  { code: '7240', name: 'Долгосрочные отсроченные обязательства по налогам и другим обязательным платежам', type: AccountType.PASSIVE },
  { code: '7250', name: 'Долгосрочные обязательства по отсроченному налогу на прибыль по временным разницам', type: AccountType.PASSIVE },
  { code: '7290', name: 'Прочие долгосрочные отсроченные обязательства', type: AccountType.PASSIVE },
  { code: '7300', name: 'СЧЕТА УЧЁТА АВАНСОВ, ПОЛУЧЕННЫХ ОТ ПОКУПАТЕЛЕЙ И ЗАКАЗЧИКОВ', type: AccountType.PASSIVE },
  { code: '7310', name: 'Авансы, полученные от покупателей и заказчиков', type: AccountType.PASSIVE },
  { code: '7800', name: 'СЧЕТА УЧЁТА ДОЛГОСРОЧНЫХ КРЕДИТОВ И ЗАЙМОВ', type: AccountType.PASSIVE },
  { code: '7810', name: 'Долгосрочные банковские кредиты', type: AccountType.PASSIVE },
  { code: '7820', name: 'Долгосрочные займы', type: AccountType.PASSIVE },
  { code: '7830', name: 'Облигации к оплате', type: AccountType.PASSIVE },
  { code: '7840', name: 'Векселя к оплате', type: AccountType.PASSIVE },
  { code: '7900', name: 'СЧЕТА УЧЁТА ДОЛГОСРОЧНОЙ ЗАДОЛЖЕННОСТИ РАЗНЫМ КРЕДИТОРАМ', type: AccountType.PASSIVE },
  { code: '7910', name: 'Финансовая аренда к оплате', type: AccountType.PASSIVE },
  { code: '7920', name: 'Прочие долгосрочные задолженности разным кредиторам', type: AccountType.PASSIVE },
  { code: '8300', name: 'СЧЕТА УЧЁТА УСТАВНОГО КАПИТАЛА', type: AccountType.PASSIVE },
  { code: '8310', name: 'Простые акции', type: AccountType.PASSIVE },
  { code: '8320', name: 'Привилегированные акции', type: AccountType.PASSIVE },
  { code: '8330', name: 'Паи и вклады', type: AccountType.PASSIVE },
  { code: '8400', name: 'СЧЕТА УЧЁТА ДОБАВЛЕННОГО КАПИТАЛА', type: AccountType.PASSIVE },
  { code: '8410', name: 'Эмиссионный доход', type: AccountType.PASSIVE },
  { code: '8420', name: 'Курсовая разница при формировании уставного капитала', type: AccountType.PASSIVE },
  { code: '8500', name: 'СЧЕТА УЧЁТА РЕЗЕРВНОГО КАПИТАЛА', type: AccountType.PASSIVE },
  { code: '8510', name: 'Корректировки по переоценке долгосрочных активов', type: AccountType.PASSIVE },
  { code: '8520', name: 'Резервный капитал (фонд)', type: AccountType.PASSIVE },
  { code: '8530', name: 'Безвозмездно полученное имущество', type: AccountType.PASSIVE },
  { code: '8600', name: 'СЧЕТА УЧЁТА ВЫКУПЛЕННЫХ СОБСТВЕННЫХ АКЦИЙ', type: AccountType.PASSIVE },
  { code: '8610', name: 'Выкупленные собственные акции — простые', type: AccountType.PASSIVE },
  { code: '8620', name: 'Выкупленные собственные акции — привилегированные', type: AccountType.PASSIVE },
  { code: '8700', name: 'СЧЕТА УЧЁТА НЕРАСПРЕДЕЛЁННОЙ ПРИБЫЛИ (НЕПОКРЫТОГО УБЫТКА)', type: AccountType.PASSIVE },
  { code: '8710', name: 'Нераспределённая прибыль (непокрытый убыток) отчётного периода', type: AccountType.PASSIVE },
  { code: '8720', name: 'Накопленная прибыль (непокрытый убыток)', type: AccountType.PASSIVE },
  { code: '8800', name: 'СЧЕТА УЧЁТА ЦЕЛЕВЫХ ПОСТУПЛЕНИЙ', type: AccountType.PASSIVE },
  { code: '8810', name: 'Гранты', type: AccountType.PASSIVE },
  { code: '8820', name: 'Субсидии', type: AccountType.PASSIVE },
  { code: '8830', name: 'Членские взносы', type: AccountType.PASSIVE },
  { code: '8840', name: 'Налоговые льготы с целевым использованием', type: AccountType.PASSIVE },
  { code: '8890', name: 'Прочие целевые поступления', type: AccountType.PASSIVE },
  { code: '8900', name: 'СЧЕТА УЧЁТА РЕЗЕРВОВ ПРЕДСТОЯЩИХ РАСХОДОВ И ПЛАТЕЖЕЙ', type: AccountType.PASSIVE },
  { code: '8910', name: 'Резервы предстоящих расходов и платежей', type: AccountType.PASSIVE },
  { code: '9000', name: 'СЧЕТА УЧЁТА ДОХОДОВ ОТ ОСНОВНОЙ (ОПЕРАЦИОННОЙ) ДЕЯТЕЛЬНОСТИ', type: AccountType.ACTIVE },
  { code: '9010', name: 'Доходы от реализации готовой продукции', type: AccountType.ACTIVE },
  { code: '9020', name: 'Доходы от реализации товаров', type: AccountType.ACTIVE },
  { code: '9030', name: 'Доходы от выполнения работ и оказания услуг', type: AccountType.ACTIVE },
  { code: '9040', name: 'Возврат проданных товаров', type: AccountType.ACTIVE },
  { code: '9050', name: 'Скидки, предоставленные покупателям и заказчикам', type: AccountType.ACTIVE },
  { code: '9100', name: 'СЧЕТА УЧЁТА СЕБЕСТОИМОСТИ РЕАЛИЗОВАННОЙ ПРОДУКЦИИ (ТОВАРОВ, РАБОТ, УСЛУГ)', type: AccountType.ACTIVE },
  { code: '9110', name: 'Себестоимость реализованной готовой продукции', type: AccountType.ACTIVE },
  { code: '9120', name: 'Себестоимость реализованных товаров', type: AccountType.ACTIVE },
  { code: '9130', name: 'Себестоимость выполненных работ и оказанных услуг', type: AccountType.ACTIVE },
  { code: '9140', name: 'Приобретение/покупка ТМЗ при периодическом учёте', type: AccountType.ACTIVE },
  { code: '9150', name: 'Корректировки по ТМЗ при периодическом учёте', type: AccountType.ACTIVE },
  { code: '9200', name: 'СЧЕТА УЧЁТА ВЫБЫТИЯ ОСНОВНЫХ СРЕДСТВ И ДРУГИХ АКТИВОВ', type: AccountType.ACTIVE },
  { code: '9210', name: 'Выбытие основных средств', type: AccountType.ACTIVE },
  { code: '9220', name: 'Выбытие прочих активов', type: AccountType.ACTIVE },
  { code: '9300', name: 'СЧЕТА УЧЁТА ПРОЧИХ ДОХОДОВ ОТ ОСНОВНОЙ ДЕЯТЕЛЬНОСТИ', type: AccountType.PASSIVE },
  { code: '9310', name: 'Прибыль от выбытия основных средств', type: AccountType.PASSIVE },
  { code: '9320', name: 'Прибыль от выбытия прочих активов', type: AccountType.PASSIVE },
  { code: '9330', name: 'Взысканные пени, штрафы, неустойки', type: AccountType.PASSIVE },
  { code: '9340', name: 'Прибыли прошлых лет', type: AccountType.PASSIVE },
  { code: '9350', name: 'Доходы от оперативной аренды', type: AccountType.PASSIVE },
  { code: '9360', name: 'Доходы от списания кредиторской и депонентской задолженности', type: AccountType.PASSIVE },
  { code: '9370', name: 'Доходы обслуживающих хозяйств', type: AccountType.PASSIVE },
  { code: '9380', name: 'Безвозмездная финансовая помощь', type: AccountType.PASSIVE },
  { code: '9390', name: 'Прочие операционные доходы', type: AccountType.PASSIVE },
  { code: '9400', name: 'СЧЕТА УЧЁТА РАСХОДОВ ПЕРИОДА', type: AccountType.ACTIVE },
  { code: '9410', name: 'Расходы по реализации', type: AccountType.ACTIVE },
  { code: '9420', name: 'Административные расходы', type: AccountType.ACTIVE },
  { code: '9430', name: 'Прочие операционные расходы', type: AccountType.ACTIVE },
  { code: '9440', name: 'Расходы отчётного периода, исключаемые из налогооблагаемой базы в будущем', type: AccountType.ACTIVE },
  { code: '9500', name: 'СЧЕТА УЧЁТА ДОХОДОВ ОТ ФИНАНСОВОЙ ДЕЯТЕЛЬНОСТИ', type: AccountType.PASSIVE },
  { code: '9510', name: 'Доходы в виде роялти', type: AccountType.PASSIVE },
  { code: '9520', name: 'Доходы в виде дивидендов', type: AccountType.PASSIVE },
  { code: '9530', name: 'Доходы в виде процентов', type: AccountType.PASSIVE },
  { code: '9540', name: 'Доходы от валютных курсовых разниц', type: AccountType.PASSIVE },
  { code: '9550', name: 'Доходы от финансовой аренды', type: AccountType.PASSIVE },
  { code: '9560', name: 'Доходы от переоценки ценных бумаг', type: AccountType.PASSIVE },
  { code: '9590', name: 'Прочие доходы от финансовой деятельности', type: AccountType.PASSIVE },
  { code: '9600', name: 'СЧЕТА УЧЁТА РАСХОДОВ ПО ФИНАНСОВОЙ ДЕЯТЕЛЬНОСТИ', type: AccountType.ACTIVE },
  { code: '9610', name: 'Расходы в виде процентов', type: AccountType.ACTIVE },
  { code: '9620', name: 'Убытки от валютных курсовых разниц', type: AccountType.ACTIVE },
  { code: '9630', name: 'Расходы по выпуску и распространению ценных бумаг', type: AccountType.ACTIVE },
  { code: '9690', name: 'Прочие расходы по финансовой деятельности', type: AccountType.ACTIVE },
  { code: '9700', name: 'СЧЕТА УЧЁТА ЧРЕЗВЫЧАЙНЫХ ПРИБЫЛЕЙ (УБЫТКОВ)', type: AccountType.ACTIVE },
  { code: '9710', name: 'Чрезвычайные прибыли', type: AccountType.ACTIVE },
  { code: '9720', name: 'Чрезвычайные убытки', type: AccountType.ACTIVE },
  { code: '9800', name: 'СЧЕТА УЧЁТА ИСПОЛЬЗОВАНИЯ ПРИБЫЛИ ДЛЯ УПЛАТЫ НАЛОГОВ И ДРУГИХ ОБЯЗАТЕЛЬНЫХ ПЛАТЕЖЕЙ', type: AccountType.ACTIVE },
  { code: '9810', name: 'Расходы по налогу на прибыль', type: AccountType.ACTIVE },
  { code: '9820', name: 'Расходы по прочим налогам и другим обязательным платежам от прибыли', type: AccountType.ACTIVE },
  { code: '9900', name: 'СЧЕТА УЧЁТА КОНЕЧНОГО ФИНАНСОВОГО РЕЗУЛЬТАТА', type: AccountType.PASSIVE },
  { code: '9910', name: 'Конечный финансовый результат', type: AccountType.PASSIVE },
  { code: '001', name: 'Основные средства, полученные по оперативной аренде', type: AccountType.ACTIVE },
  { code: '002', name: 'Товарно-материальные ценности, принятые на ответственное хранение', type: AccountType.ACTIVE },
  { code: '003', name: 'Материалы, принятые в переработку', type: AccountType.ACTIVE },
  { code: '004', name: 'Товары, принятые на комиссию', type: AccountType.ACTIVE },
  { code: '005', name: 'Оборудование, принятое для монтажа', type: AccountType.ACTIVE },
  { code: '006', name: 'Бланки строгой отчётности', type: AccountType.ACTIVE },
  { code: '007', name: 'Списанная в убыток задолженность неплатёжеспособных дебиторов', type: AccountType.ACTIVE },
  { code: '008', name: 'Обеспечения обязательств и платежей — полученные', type: AccountType.ACTIVE },
  { code: '009', name: 'Обеспечения обязательств и платежей — выданные', type: AccountType.ACTIVE },
  { code: '010', name: 'Основные средства, сданные по договору финансовой аренды', type: AccountType.ACTIVE },
  { code: '011', name: 'Имущество, полученное по договору ссуды', type: AccountType.ACTIVE },
  { code: '012', name: 'Расходы, исключаемые из налогооблагаемой базы следующих периодов', type: AccountType.ACTIVE },
  { code: '013', name: 'Временные налоговые льготы (по видам)', type: AccountType.ACTIVE },
  { code: '014', name: 'Инвентарь и хозяйственные принадлежности в эксплуатации', type: AccountType.ACTIVE },
  { code: '015', name: 'Имущество, полученное по договору простого товарищества (совместной деятельности)', type: AccountType.ACTIVE },
  { code: '016', name: 'Нематериальные активы, полученные по праву пользования', type: AccountType.ACTIVE },
]

export async function seedDefaultDataForOrg(organizationId: string) {
  // 1. Seed Accounts
  for (const account of defaultAccounts) {
    const masterAccount = await prisma.masterAccount.findUnique({
      where: { code: account.code }
    });

    await prisma.account.upsert({
      where: { 
        code_organization_id: {
          code: account.code,
          organization_id: organizationId
        }
      },
      update: { 
        name: account.name, 
        type: account.type,
        master_account_id: masterAccount?.id || null 
      },
      create: {
        ...account,
        organization_id: organizationId,
        master_account_id: masterAccount?.id || null
      },
    })
  }

  // 2. Initial system settings
  await prisma.systemSettings.upsert({
    where: { organization_id: organizationId },
    update: {},
    create: {
      closed_period_date: new Date('2024-01-01'),
      organization_id: organizationId
    },
  })
}
