version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: contador-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contador
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: contador-app
    container_name: contador-app
    restart: always
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/contador
      NEXT_PUBLIC_PORT: 3030
      BASIC_AUTH_USER: admin
      BASIC_AUTH_PASSWORD: securepassword
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    image: contador-admin
    container_name: contador-admin
    restart: always
    ports:
      - "3031:3031"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/contador
      ADMIN_PORT: 3031
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - db
